services:
  - type: web          # Define the type of service
    name: web
    plan: starter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT app:app
